# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tradeui.ui'
#
# Created: Thu Apr 15 15:06:15 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 612)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stock = QtGui.QTableView(self.tab)
        self.stock.setObjectName("stock")
        self.horizontalLayout.addWidget(self.stock)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 19))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtGui.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.import_portfolio = QtGui.QAction(MainWindow)
        self.import_portfolio.setObjectName("import_portfolio")
        self.buybatch = QtGui.QAction(MainWindow)
        self.buybatch.setObjectName("buybatch")
        self.prices1 = QtGui.QAction(MainWindow)
        self.prices1.setObjectName("prices1")
        self.prices2 = QtGui.QAction(MainWindow)
        self.prices2.setObjectName("prices2")
        self.pricelatest = QtGui.QAction(MainWindow)
        self.pricelatest.setObjectName("pricelatest")
        self.prices3 = QtGui.QAction(MainWindow)
        self.prices3.setObjectName("prices3")
        self.prices4 = QtGui.QAction(MainWindow)
        self.prices4.setObjectName("prices4")
        self.prices5 = QtGui.QAction(MainWindow)
        self.prices5.setObjectName("prices5")
        self.priceb1 = QtGui.QAction(MainWindow)
        self.priceb1.setObjectName("priceb1")
        self.priceb2 = QtGui.QAction(MainWindow)
        self.priceb2.setObjectName("priceb2")
        self.priceb3 = QtGui.QAction(MainWindow)
        self.priceb3.setObjectName("priceb3")
        self.priceb4 = QtGui.QAction(MainWindow)
        self.priceb4.setObjectName("priceb4")
        self.priceb5 = QtGui.QAction(MainWindow)
        self.priceb5.setObjectName("priceb5")
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.save_order = QtGui.QAction(MainWindow)
        self.save_order.setObjectName("save_order")
        self.cancel_order = QtGui.QAction(MainWindow)
        self.cancel_order.setObjectName("cancel_order")
        self.gen_backuporder = QtGui.QAction(MainWindow)
        self.gen_backuporder.setObjectName("gen_backuporder")
        self.menuImport.addAction(self.import_portfolio)
        self.menuImport.addAction(self.save_order)
        self.menu.addAction(self.buybatch)
        self.menu.addAction(self.cancel_order)
        self.menu.addAction(self.gen_backuporder)
        self.menu_2.addAction(self.pricelatest)
        self.menu_2.addAction(self.prices1)
        self.menu_2.addAction(self.prices2)
        self.menu_2.addAction(self.prices3)
        self.menu_2.addAction(self.prices4)
        self.menu_2.addAction(self.prices5)
        self.menu_2.addAction(self.priceb1)
        self.menu_2.addAction(self.priceb2)
        self.menu_2.addAction(self.priceb3)
        self.menu_2.addAction(self.priceb4)
        self.menu_2.addAction(self.priceb5)
        self.menu_2.addAction(self.action_13)
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EasyTrader", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "投资组合", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport.setTitle(QtGui.QApplication.translate("MainWindow", "文件", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "组合操作", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "报价策略", None, QtGui.QApplication.UnicodeUTF8))
        self.import_portfolio.setText(QtGui.QApplication.translate("MainWindow", "导入组合", None, QtGui.QApplication.UnicodeUTF8))
        self.buybatch.setText(QtGui.QApplication.translate("MainWindow", "委托买入", None, QtGui.QApplication.UnicodeUTF8))
        self.prices1.setText(QtGui.QApplication.translate("MainWindow", "卖一", None, QtGui.QApplication.UnicodeUTF8))
        self.prices2.setText(QtGui.QApplication.translate("MainWindow", "卖二", None, QtGui.QApplication.UnicodeUTF8))
        self.pricelatest.setText(QtGui.QApplication.translate("MainWindow", "最新价", None, QtGui.QApplication.UnicodeUTF8))
        self.prices3.setText(QtGui.QApplication.translate("MainWindow", "卖三", None, QtGui.QApplication.UnicodeUTF8))
        self.prices4.setText(QtGui.QApplication.translate("MainWindow", "卖四", None, QtGui.QApplication.UnicodeUTF8))
        self.prices5.setText(QtGui.QApplication.translate("MainWindow", "卖五", None, QtGui.QApplication.UnicodeUTF8))
        self.priceb1.setText(QtGui.QApplication.translate("MainWindow", "买一", None, QtGui.QApplication.UnicodeUTF8))
        self.priceb2.setText(QtGui.QApplication.translate("MainWindow", "买二", None, QtGui.QApplication.UnicodeUTF8))
        self.priceb3.setText(QtGui.QApplication.translate("MainWindow", "买三", None, QtGui.QApplication.UnicodeUTF8))
        self.priceb4.setText(QtGui.QApplication.translate("MainWindow", "买四", None, QtGui.QApplication.UnicodeUTF8))
        self.priceb5.setText(QtGui.QApplication.translate("MainWindow", "买五", None, QtGui.QApplication.UnicodeUTF8))
        self.action_13.setText(QtGui.QApplication.translate("MainWindow", "自定义", None, QtGui.QApplication.UnicodeUTF8))
        self.save_order.setText(QtGui.QApplication.translate("MainWindow", "保存委托", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_order.setText(QtGui.QApplication.translate("MainWindow", "撤销未成交委托", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_backuporder.setText(QtGui.QApplication.translate("MainWindow", "生成补单", None, QtGui.QApplication.UnicodeUTF8))

