# define constants for flare library

# namespaces
ORDERNS = 'ORDER'
TRADENS = 'TRADE'
PTFNOMNS = 'PTFNOM'
PTFRENS = 'PTFRLZ'
ORD2TRDNS = 'ORD2TRD'

# global keys
ALLORDERS = 'ALLORDERS'
ALLTRADES = 'ALLTRADES'
ALLPTFRES = 'ALLPTFRES'
ALLPTFNOM = 'ALLPTFNOM'

FRONTIDKB = 'ALLFRONT'
SESSIONIDKB = 'ALLSESSION'
