# How is the price patterns correlated with scalpel success rate?

# using .stat generated by scpstat.py

args = commandArgs(T)

statfn = '20140808/scpstrat1.2014-08-08.stat'
pdfn = '20140808/scpstrat1.2014-08-08.pattern.pdf'

if(length(args) >= 2)
{
  statfn = args[1]
  pdfn = args[2]
}

# read .stat file

stat = read.csv(statfn, header=T)
stat.m = as.matrix(stat)

# define context by define start/end points
context = matrix(c(4,1,
                   6,1,
                   8,1,
                   5,2,
                   7,2,
                   9,2), ncol=2, byrow=T)

# for each predefined `context', cluster the contexts and see whether some group is
# better at doing scalpel.

seequote = stat$seequote

for(i in 1:NROW(context))
{
  # select all contexts
  start = context[i,1]
  end = context[i,2]

  if (stat$tdir[1]==-1)
  {
    # ask price trend
    prices = stat.m[,paste('ask', start:end, sep='')]
  } else
  {
    prices = stat.m[,paste('bid', start:end, sep='')]
  }
  pd = t(apply(prices, 1, diff))
  # cluster into 10 groups, 10 by manual selection.
  fit = kmeans(pd, 10)
  
  # see if correlated with scalpel success rate
  for(c in fit$cluster)
  {
    
  }
}

