# plot stat generated by scpstat.py

args = commandArgs(T)

statfn = '20140812/scpstrat1.2014-08-12.stat'
pdfn = 'scpstrat1.2014-08-12.stat.pdf'

if(length(args) >= 2)
{
  statfn = args[1]
  pdfn = args[2]
}

stat = read.csv(statfn, header=T)

statpdf = pdf(pdfn, width=17.55, height=11.07)

# time dist between set-open
hist(stat$open-stat$set, breaks=50, main='timedelta of set-open')

# time dist between open-close
hist(stat$close-stat$open, breaks=50, main='timedelta of open-close')

# time dist between set-close
hist(stat$close-stat$set, breaks=50, main='timedelta of set-close')

# earn vs set-close time delta
plot(stat$close-stat$set, stat$earn, main='earn vs set-close timedelta')

# earn vs open-close time delta
plot(stat$close-stat$open, stat$earn, main='earn vs open-close timedelta')

# earn vs set-open time delta
plot(stat$open-stat$set, stat$earn, main='earn vs set-open timedelta')

# bidvol1 hist
hist(stat$bidvol, breaks=20, main='bid vol')
hist(log10(stat$bidvol), breaks=20, main='bid vol, log10')

# earn vs bidvol
plot(log10(stat$bidvol), stat$earn, main='earn vs bidvol')

# askvol1 hist
hist(stat$askvol, breaks=20, main='ask vol')
hist(log10(stat$askvol), breaks=20, main='ask vol, log10')

# earn vs askvol
plot(log10(stat$askvol), stat$earn, main='earn vs askvol')

# stat$askvbid hist
hist(stat$askvbid, breaks=20, main='askvol/bidvol')
hist(log10(stat$askvbid), breaks=20, main='askvol/bidvol, log10')

# earn vs askvol/bidvol
plot(log10(stat$askvbid), stat$earn, main='earn vs askvol/bidvol')

dev.off()

# $Id$
