# plot stat generated by scpstat.py

library(ggplot2)

args = commandArgs(T)

statfn = '20140812/scpstrat1.2014-08-12.stat'
pdfn = 'scpstrat1.2014-08-12.stat2.pdf'

if(length(args) >= 2)
{
  statfn = args[1]
  pdfn = args[2]
}

trend <- function(p, tnum)
{
  y = p
  x = 1:tnum
  lmr = lm(y~x)
  return(coef(lmr)[2])
}

stat = read.csv(statfn, header=T)
stat.m = as.matrix(stat)

# prepare datas: prices and volumes
if (stat$tdir[1]==-1)
{
  # ask price trend
  prices3 = stat[,paste('ask', 3:1, sep='')]
  prices5 = stat[,paste('ask', 5:1, sep='')]
  prices7 = stat[,paste('ask', 7:1, sep='')]
  
  same3 = stat[,paste('askvol', 3:1, sep='')]
  same5 = stat[,paste('askvol', 5:1, sep='')]
  same7 = stat[,paste('askvol', 7:1, sep='')]

  oppo3 = stat[,paste('bidvol', 3:1, sep='')]
  oppo5 = stat[,paste('bidvol', 5:1, sep='')]
  oppo7 = stat[,paste('bidvol', 7:1, sep='')]
} else
{
  prices3 = stat[,paste('bid', 3:1, sep='')]
  prices5 = stat[,paste('bid', 5:1, sep='')]
  prices7 = stat[,paste('bid', 7:1, sep='')]

  same3 = stat[,paste('bidvol', 3:1, sep='')]
  same5 = stat[,paste('bidvol', 5:1, sep='')]
  same7 = stat[,paste('bidvol', 7:1, sep='')]
  
  oppo3 = stat[,paste('askvol', 3:1, sep='')]
  oppo5 = stat[,paste('askvol', 5:1, sep='')]
  oppo7 = stat[,paste('askvol', 7:1, sep='')]
}

# tick trends vs earning

trend3 = apply(prices3, 1, FUN=trend, 3)
trend5 = apply(prices5, 1, FUN=trend, 5)
trend7 = apply(prices7, 1, FUN=trend, 7)

# same side orderbook volume, absolute number and ratio to opposite volume

lastnum = same3[,3]
lastratio = same3[,3]/oppo3[,3]

last3num.max = apply(same3, 1, FUN=max)
last3num.avg = apply(same3, 1, FUN=mean)
last3ratio.max = apply(same3/oppo3, 1, FUN=max)
last3ratio.avg = apply(same3/oppo3, 1, FUN=mean)

last5num.max = apply(same5, 1, FUN=max)
last5num.avg = apply(same5, 1, FUN=mean)
last5ratio.max = apply(same5/oppo5, 1, FUN=max)
last5ratio.avg = apply(same5/oppo5, 1, FUN=mean)

last7num.max = apply(same7, 1, FUN=max)
last7num.avg = apply(same7, 1, FUN=mean)
last7ratio.max = apply(same7/oppo7, 1, FUN=max)
last7ratio.avg = apply(same7/oppo7, 1, FUN=mean)

# opposite orderbook volume, absolute number and ratio to same side volume

statpdf = pdf(pdfn, width=17.55, height=11.07)

earn = stat$earn

plot(trend3, earn)
plot(trend5, earn)
plot(trend7, earn)

ggplot(data.frame(lastnum, earn), aes(x=log(lastnum), fill=earn)) + geom_bar(stat='bin', color='lightgrey')

plot(lastnum, earn)
plot(lastratio, earn)

plot(last3num.max, earn)
plot(last3num.avg, earn)
plot(last3ratio.max, earn)
plot(last3ratio.avg, earn)

plot(last5num.max, earn)
plot(last5num.avg, earn)
plot(last5ratio.max, earn)
plot(last5ratio.avg, earn)

plot(last7num.max, earn)
plot(last7num.avg, earn)
plot(last7ratio.max, earn)
plot(last7ratio.avg, earn)

dev.off()

# $Id$
