# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'positioninfoui.ui'
#
# Created: Wed Sep 15 14:47:12 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_positioninfodlg(object):
    def setupUi(self, positioninfodlg):
        positioninfodlg.setObjectName("positioninfodlg")
        positioninfodlg.resize(305, 238)
        positioninfodlg.setModal(False)
        self.gridLayout = QtGui.QGridLayout(positioninfodlg)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(positioninfodlg)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.totalcost = QtGui.QLineEdit(self.groupBox)
        self.totalcost.setFrame(True)
        self.totalcost.setReadOnly(True)
        self.totalcost.setObjectName("totalcost")
        self.gridLayout_2.addWidget(self.totalcost, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.mktval = QtGui.QLineEdit(self.groupBox)
        self.mktval.setFrame(True)
        self.mktval.setReadOnly(True)
        self.mktval.setObjectName("mktval")
        self.gridLayout_2.addWidget(self.mktval, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.profitval = QtGui.QLineEdit(self.groupBox)
        self.profitval.setFrame(True)
        self.profitval.setReadOnly(True)
        self.profitval.setObjectName("profitval")
        self.gridLayout_2.addWidget(self.profitval, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.profitper = QtGui.QLineEdit(self.groupBox)
        self.profitper.setFrame(True)
        self.profitper.setReadOnly(True)
        self.profitper.setObjectName("profitper")
        self.gridLayout_2.addWidget(self.profitper, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.sigain = QtGui.QLineEdit(self.groupBox)
        self.sigain.setFrame(True)
        self.sigain.setReadOnly(True)
        self.sigain.setObjectName("sigain")
        self.gridLayout_2.addWidget(self.sigain, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.totalgain = QtGui.QLineEdit(self.groupBox)
        self.totalgain.setFrame(True)
        self.totalgain.setReadOnly(True)
        self.totalgain.setObjectName("totalgain")
        self.gridLayout_2.addWidget(self.totalgain, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(171, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.refresh = QtGui.QPushButton(positioninfodlg)
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 1, 1, 1, 1)
        self.ok = QtGui.QPushButton(positioninfodlg)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 1, 2, 1, 1)

        self.retranslateUi(positioninfodlg)
        QtCore.QMetaObject.connectSlotsByName(positioninfodlg)

    def retranslateUi(self, positioninfodlg):
        positioninfodlg.setWindowTitle(QtGui.QApplication.translate("positioninfodlg", "盈亏统计", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("positioninfodlg", "持仓信息（括号内数值减去了停牌股票市值）", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("positioninfodlg", "买入成本：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("positioninfodlg", "持仓市值：", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("positioninfodlg", "盈亏值：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("positioninfodlg", "盈亏比：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("positioninfodlg", "期货盈亏", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("positioninfodlg", "总盈亏", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("positioninfodlg", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.ok.setText(QtGui.QApplication.translate("positioninfodlg", "确定", None, QtGui.QApplication.UnicodeUTF8))

