# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tradeui.ui'
#
# Created: Mon Oct 11 09:59:06 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1277, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ztzq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/img/ztzq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.optab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optab.sizePolicy().hasHeightForWidth())
        self.optab.setSizePolicy(sizePolicy)
        self.optab.setObjectName("optab")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pricepolicybuy = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pricepolicybuy.sizePolicy().hasHeightForWidth())
        self.pricepolicybuy.setSizePolicy(sizePolicy)
        self.pricepolicybuy.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pricepolicybuy.setObjectName("pricepolicybuy")
        self.gridLayout_2.addWidget(self.pricepolicybuy, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.buyorder = QtGui.QPushButton(self.groupBox_2)
        self.buyorder.setObjectName("buyorder")
        self.gridLayout_2.addWidget(self.buyorder, 0, 4, 1, 1)
        self.cancelbuyorder = QtGui.QPushButton(self.groupBox_2)
        self.cancelbuyorder.setObjectName("cancelbuyorder")
        self.gridLayout_2.addWidget(self.cancelbuyorder, 0, 6, 1, 1)
        self.autosubmit_2 = QtGui.QPushButton(self.groupBox_2)
        self.autosubmit_2.setObjectName("autosubmit_2")
        self.gridLayout_2.addWidget(self.autosubmit_2, 0, 8, 1, 1)
        self.buypricefixspin = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buypricefixspin.sizePolicy().hasHeightForWidth())
        self.buypricefixspin.setSizePolicy(sizePolicy)
        self.buypricefixspin.setMinimumSize(QtCore.QSize(80, 0))
        self.buypricefixspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buypricefixspin.setFrame(True)
        self.buypricefixspin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.buypricefixspin.setMinimum(-999.99)
        self.buypricefixspin.setMaximum(999.99)
        self.buypricefixspin.setSingleStep(0.01)
        self.buypricefixspin.setObjectName("buypricefixspin")
        self.gridLayout_2.addWidget(self.buypricefixspin, 0, 3, 1, 1)
        self.forcecancelbuychk = QtGui.QCheckBox(self.groupBox_2)
        self.forcecancelbuychk.setObjectName("forcecancelbuychk")
        self.gridLayout_2.addWidget(self.forcecancelbuychk, 0, 7, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_32.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 0, 1, 1)
        self.buyorder2 = QtGui.QPushButton(self.groupBox_2)
        self.buyorder2.setObjectName("buyorder2")
        self.gridLayout_2.addWidget(self.buyorder2, 0, 5, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.opensifbtn = QtGui.QPushButton(self.groupBox_5)
        self.opensifbtn.setObjectName("opensifbtn")
        self.gridLayout_7.addWidget(self.opensifbtn, 0, 3, 1, 1)
        self.cancelopensifbtn = QtGui.QPushButton(self.groupBox_5)
        self.cancelopensifbtn.setObjectName("cancelopensifbtn")
        self.gridLayout_7.addWidget(self.cancelopensifbtn, 0, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 1, 1, 1)
        self.openpricecmbox = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openpricecmbox.sizePolicy().hasHeightForWidth())
        self.openpricecmbox.setSizePolicy(sizePolicy)
        self.openpricecmbox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.openpricecmbox.setObjectName("openpricecmbox")
        self.gridLayout_7.addWidget(self.openpricecmbox, 0, 0, 1, 1)
        self.openpricefixspin = QtGui.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openpricefixspin.sizePolicy().hasHeightForWidth())
        self.openpricefixspin.setSizePolicy(sizePolicy)
        self.openpricefixspin.setMinimumSize(QtCore.QSize(80, 0))
        self.openpricefixspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.openpricefixspin.setFrame(True)
        self.openpricefixspin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.openpricefixspin.setPrefix("")
        self.openpricefixspin.setDecimals(1)
        self.openpricefixspin.setMinimum(-10000.0)
        self.openpricefixspin.setMaximum(10000.0)
        self.openpricefixspin.setSingleStep(0.2)
        self.openpricefixspin.setObjectName("openpricefixspin")
        self.gridLayout_7.addWidget(self.openpricefixspin, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.sopenspin = QtGui.QSpinBox(self.groupBox_6)
        self.sopenspin.setObjectName("sopenspin")
        self.gridLayout_9.addWidget(self.sopenspin, 0, 0, 1, 1)
        self.sopenbtn = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sopenbtn.sizePolicy().hasHeightForWidth())
        self.sopenbtn.setSizePolicy(sizePolicy)
        self.sopenbtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sopenbtn.setObjectName("sopenbtn")
        self.gridLayout_9.addWidget(self.sopenbtn, 0, 1, 1, 1)
        self.lopenbtn = QtGui.QPushButton(self.groupBox_6)
        self.lopenbtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lopenbtn.setObjectName("lopenbtn")
        self.gridLayout_9.addWidget(self.lopenbtn, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 2, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/rdot.jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/img/grdot.jpg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.optab.addTab(self.tab, icon1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pricepolicysell = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pricepolicysell.sizePolicy().hasHeightForWidth())
        self.pricepolicysell.setSizePolicy(sizePolicy)
        self.pricepolicysell.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pricepolicysell.setObjectName("pricepolicysell")
        self.gridLayout.addWidget(self.pricepolicysell, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.sellorder = QtGui.QPushButton(self.groupBox)
        self.sellorder.setObjectName("sellorder")
        self.gridLayout.addWidget(self.sellorder, 0, 4, 1, 1)
        self.cancelsellorder = QtGui.QPushButton(self.groupBox)
        self.cancelsellorder.setObjectName("cancelsellorder")
        self.gridLayout.addWidget(self.cancelsellorder, 0, 6, 1, 1)
        self.autosubmit = QtGui.QPushButton(self.groupBox)
        self.autosubmit.setObjectName("autosubmit")
        self.gridLayout.addWidget(self.autosubmit, 0, 8, 1, 1)
        self.sellpricefixspin = QtGui.QDoubleSpinBox(self.groupBox)
        self.sellpricefixspin.setMinimumSize(QtCore.QSize(80, 0))
        self.sellpricefixspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sellpricefixspin.setMinimum(-999.99)
        self.sellpricefixspin.setMaximum(999.99)
        self.sellpricefixspin.setSingleStep(0.01)
        self.sellpricefixspin.setObjectName("sellpricefixspin")
        self.gridLayout.addWidget(self.sellpricefixspin, 0, 3, 1, 1)
        self.forcecancelsellchk = QtGui.QCheckBox(self.groupBox)
        self.forcecancelsellchk.setObjectName("forcecancelsellchk")
        self.gridLayout.addWidget(self.forcecancelsellchk, 0, 7, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_33.setStyleSheet("color: rgb(85, 255, 0);\n"
"background-color: rgb(85, 255, 0);")
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 0, 1, 1)
        self.sellorder2 = QtGui.QPushButton(self.groupBox)
        self.sellorder2.setObjectName("sellorder2")
        self.gridLayout.addWidget(self.sellorder2, 0, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.closesifbtn = QtGui.QPushButton(self.groupBox_4)
        self.closesifbtn.setObjectName("closesifbtn")
        self.gridLayout_8.addWidget(self.closesifbtn, 0, 4, 1, 1)
        self.cancelclosesifbtn = QtGui.QPushButton(self.groupBox_4)
        self.cancelclosesifbtn.setObjectName("cancelclosesifbtn")
        self.gridLayout_8.addWidget(self.cancelclosesifbtn, 0, 5, 1, 1)
        self.closepricecmbox = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closepricecmbox.sizePolicy().hasHeightForWidth())
        self.closepricecmbox.setSizePolicy(sizePolicy)
        self.closepricecmbox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.closepricecmbox.setObjectName("closepricecmbox")
        self.gridLayout_8.addWidget(self.closepricecmbox, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 2, 1, 1)
        self.closepricefixspin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.closepricefixspin.setMinimumSize(QtCore.QSize(80, 0))
        self.closepricefixspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.closepricefixspin.setPrefix("")
        self.closepricefixspin.setDecimals(1)
        self.closepricefixspin.setMinimum(-10000.0)
        self.closepricefixspin.setMaximum(10000.0)
        self.closepricefixspin.setSingleStep(0.2)
        self.closepricefixspin.setObjectName("closepricefixspin")
        self.gridLayout_8.addWidget(self.closepricefixspin, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.sclosespin = QtGui.QSpinBox(self.groupBox_7)
        self.sclosespin.setObjectName("sclosespin")
        self.gridLayout_10.addWidget(self.sclosespin, 0, 0, 1, 1)
        self.sclosebtn = QtGui.QPushButton(self.groupBox_7)
        self.sclosebtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sclosebtn.setObjectName("sclosebtn")
        self.gridLayout_10.addWidget(self.sclosebtn, 0, 1, 1, 1)
        self.lclosebtn = QtGui.QPushButton(self.groupBox_7)
        self.lclosebtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lclosebtn.setObjectName("lclosebtn")
        self.gridLayout_10.addWidget(self.lclosebtn, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 2, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/gdot.jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/img/grdot.jpg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.optab.addTab(self.tab_2, icon2, "")
        self.gridLayout_11.addWidget(self.optab, 0, 0, 1, 12)
        self.stockindex = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockindex.sizePolicy().hasHeightForWidth())
        self.stockindex.setSizePolicy(sizePolicy)
        self.stockindex.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stockindex.setObjectName("stockindex")
        self.gridLayout_11.addWidget(self.stockindex, 1, 0, 1, 12)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.hs300line = QtGui.QLineEdit(self.groupBox_3)
        self.hs300line.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hs300line.sizePolicy().hasHeightForWidth())
        self.hs300line.setSizePolicy(sizePolicy)
        self.hs300line.setMinimumSize(QtCore.QSize(0, 0))
        self.hs300line.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hs300line.setReadOnly(True)
        self.hs300line.setObjectName("hs300line")
        self.gridLayout_5.addWidget(self.hs300line, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 2, 1, 1)
        self.sindexcmbox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sindexcmbox.sizePolicy().hasHeightForWidth())
        self.sindexcmbox.setSizePolicy(sizePolicy)
        self.sindexcmbox.setObjectName("sindexcmbox")
        self.gridLayout_5.addWidget(self.sindexcmbox, 0, 3, 1, 1)
        self.sindexline = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sindexline.sizePolicy().hasHeightForWidth())
        self.sindexline.setSizePolicy(sizePolicy)
        self.sindexline.setMinimumSize(QtCore.QSize(0, 0))
        self.sindexline.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sindexline.setReadOnly(True)
        self.sindexline.setObjectName("sindexline")
        self.gridLayout_5.addWidget(self.sindexline, 0, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 5, 1, 1)
        self.basediffline = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basediffline.sizePolicy().hasHeightForWidth())
        self.basediffline.setSizePolicy(sizePolicy)
        self.basediffline.setMinimumSize(QtCore.QSize(0, 0))
        self.basediffline.setMaximumSize(QtCore.QSize(60, 16777215))
        self.basediffline.setReadOnly(True)
        self.basediffline.setObjectName("basediffline")
        self.gridLayout_5.addWidget(self.basediffline, 0, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 15, 1, 1)
        self.basediffperline = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basediffperline.sizePolicy().hasHeightForWidth())
        self.basediffperline.setSizePolicy(sizePolicy)
        self.basediffperline.setMinimumSize(QtCore.QSize(0, 0))
        self.basediffperline.setMaximumSize(QtCore.QSize(60, 16777215))
        self.basediffperline.setReadOnly(True)
        self.basediffperline.setObjectName("basediffperline")
        self.gridLayout_5.addWidget(self.basediffperline, 0, 8, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 10, 1, 1)
        self.openthresholdspin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openthresholdspin.sizePolicy().hasHeightForWidth())
        self.openthresholdspin.setSizePolicy(sizePolicy)
        self.openthresholdspin.setMinimumSize(QtCore.QSize(80, 0))
        self.openthresholdspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.openthresholdspin.setStyleSheet("None")
        self.openthresholdspin.setFrame(True)
        self.openthresholdspin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.openthresholdspin.setPrefix("")
        self.openthresholdspin.setDecimals(1)
        self.openthresholdspin.setMinimum(0.0)
        self.openthresholdspin.setMaximum(10000.0)
        self.openthresholdspin.setSingleStep(0.1)
        self.openthresholdspin.setProperty("value", 1.5)
        self.openthresholdspin.setObjectName("openthresholdspin")
        self.gridLayout_5.addWidget(self.openthresholdspin, 0, 11, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 9, 1, 1)
        self.playsignalchk = QtGui.QCheckBox(self.groupBox_3)
        self.playsignalchk.setChecked(True)
        self.playsignalchk.setObjectName("playsignalchk")
        self.gridLayout_5.addWidget(self.playsignalchk, 0, 14, 1, 1)
        self.closethresholdspin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closethresholdspin.sizePolicy().hasHeightForWidth())
        self.closethresholdspin.setSizePolicy(sizePolicy)
        self.closethresholdspin.setMinimumSize(QtCore.QSize(80, 0))
        self.closethresholdspin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.closethresholdspin.setStyleSheet("None")
        self.closethresholdspin.setFrame(True)
        self.closethresholdspin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.closethresholdspin.setPrefix("")
        self.closethresholdspin.setDecimals(1)
        self.closethresholdspin.setMinimum(-10000.0)
        self.closethresholdspin.setMaximum(10000.0)
        self.closethresholdspin.setSingleStep(0.1)
        self.closethresholdspin.setProperty("value", 0.5)
        self.closethresholdspin.setObjectName("closethresholdspin")
        self.gridLayout_5.addWidget(self.closethresholdspin, 0, 13, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 12, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_3, 2, 0, 1, 12)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 3, 0, 1, 1)
        self.bostatusline = QtGui.QLineEdit(self.centralwidget)
        self.bostatusline.setReadOnly(True)
        self.bostatusline.setObjectName("bostatusline")
        self.gridLayout_11.addWidget(self.bostatusline, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 3, 2, 1, 1)
        self.buytotalline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buytotalline.sizePolicy().hasHeightForWidth())
        self.buytotalline.setSizePolicy(sizePolicy)
        self.buytotalline.setMinimumSize(QtCore.QSize(0, 0))
        self.buytotalline.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buytotalline.setReadOnly(True)
        self.buytotalline.setObjectName("buytotalline")
        self.gridLayout_11.addWidget(self.buytotalline, 3, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 3, 6, 1, 1)
        self.selltotalline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selltotalline.sizePolicy().hasHeightForWidth())
        self.selltotalline.setSizePolicy(sizePolicy)
        self.selltotalline.setMinimumSize(QtCore.QSize(0, 0))
        self.selltotalline.setMaximumSize(QtCore.QSize(80, 16777215))
        self.selltotalline.setReadOnly(True)
        self.selltotalline.setObjectName("selltotalline")
        self.gridLayout_11.addWidget(self.selltotalline, 3, 7, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 3, 10, 1, 1)
        self.posnameline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posnameline.sizePolicy().hasHeightForWidth())
        self.posnameline.setSizePolicy(sizePolicy)
        self.posnameline.setMinimumSize(QtCore.QSize(256, 0))
        self.posnameline.setReadOnly(True)
        self.posnameline.setObjectName("posnameline")
        self.gridLayout_11.addWidget(self.posnameline, 3, 11, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stock = QtGui.QTableView(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock.sizePolicy().hasHeightForWidth())
        self.stock.setSizePolicy(sizePolicy)
        self.stock.setObjectName("stock")
        self.gridLayout_6.addWidget(self.stock, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.logtext = QtGui.QPlainTextEdit(self.tab_6)
        self.logtext.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.logtext.setReadOnly(True)
        self.logtext.setObjectName("logtext")
        self.gridLayout_12.addWidget(self.logtext, 1, 0, 1, 2)
        self.loadlogbtn = QtGui.QPushButton(self.tab_6)
        self.loadlogbtn.setObjectName("loadlogbtn")
        self.gridLayout_12.addWidget(self.loadlogbtn, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_11.addWidget(self.tabWidget_2, 4, 0, 1, 11)
        self.tabstat = QtGui.QTabWidget(self.centralwidget)
        self.tabstat.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabstat.setObjectName("tabstat")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout = QtGui.QFormLayout(self.tab_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.stoppedline = QtGui.QLineEdit(self.tab_3)
        self.stoppedline.setReadOnly(True)
        self.stoppedline.setObjectName("stoppedline")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.stoppedline)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.buyableline = QtGui.QLineEdit(self.tab_3)
        self.buyableline.setReadOnly(True)
        self.buyableline.setObjectName("buyableline")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.buyableline)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.buyedline = QtGui.QLineEdit(self.tab_3)
        self.buyedline.setReadOnly(True)
        self.buyedline.setObjectName("buyedline")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.buyedline)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.buywaitline = QtGui.QLineEdit(self.tab_3)
        self.buywaitline.setReadOnly(True)
        self.buywaitline.setObjectName("buywaitline")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.buywaitline)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_21)
        self.buyfailline = QtGui.QLineEdit(self.tab_3)
        self.buyfailline.setReadOnly(True)
        self.buyfailline.setObjectName("buyfailline")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.buyfailline)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_22)
        self.cancelbuyfailline = QtGui.QLineEdit(self.tab_3)
        self.cancelbuyfailline.setReadOnly(True)
        self.cancelbuyfailline.setObjectName("cancelbuyfailline")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cancelbuyfailline)
        self.tabstat.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayout_2 = QtGui.QFormLayout(self.tab_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_30)
        self.stoppedline_2 = QtGui.QLineEdit(self.tab_4)
        self.stoppedline_2.setReadOnly(True)
        self.stoppedline_2.setObjectName("stoppedline_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.stoppedline_2)
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.sellableline = QtGui.QLineEdit(self.tab_4)
        self.sellableline.setReadOnly(True)
        self.sellableline.setObjectName("sellableline")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sellableline)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_28)
        self.selledline = QtGui.QLineEdit(self.tab_4)
        self.selledline.setReadOnly(True)
        self.selledline.setObjectName("selledline")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.selledline)
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_27)
        self.sellwaitline = QtGui.QLineEdit(self.tab_4)
        self.sellwaitline.setReadOnly(True)
        self.sellwaitline.setObjectName("sellwaitline")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.sellwaitline)
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_26)
        self.sellfailline = QtGui.QLineEdit(self.tab_4)
        self.sellfailline.setReadOnly(True)
        self.sellfailline.setObjectName("sellfailline")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.sellfailline)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_31)
        self.cancelsellfailline = QtGui.QLineEdit(self.tab_4)
        self.cancelsellfailline.setReadOnly(True)
        self.cancelsellfailline.setObjectName("cancelsellfailline")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.cancelsellfailline)
        self.tabstat.addTab(self.tab_4, "")
        self.gridLayout_11.addWidget(self.tabstat, 4, 11, 1, 1)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 3, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 3, 8, 1, 1)
        self.buypointline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buypointline.sizePolicy().hasHeightForWidth())
        self.buypointline.setSizePolicy(sizePolicy)
        self.buypointline.setMinimumSize(QtCore.QSize(0, 0))
        self.buypointline.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buypointline.setReadOnly(True)
        self.buypointline.setObjectName("buypointline")
        self.gridLayout_11.addWidget(self.buypointline, 3, 5, 1, 1)
        self.sellpointline = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sellpointline.sizePolicy().hasHeightForWidth())
        self.sellpointline.setSizePolicy(sizePolicy)
        self.sellpointline.setMinimumSize(QtCore.QSize(0, 0))
        self.sellpointline.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sellpointline.setReadOnly(True)
        self.sellpointline.setObjectName("sellpointline")
        self.gridLayout_11.addWidget(self.sellpointline, 3, 9, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1277, 23))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.stockinfoact = QtGui.QAction(MainWindow)
        self.stockinfoact.setObjectName("stockinfoact")
        self.posstatact = QtGui.QAction(MainWindow)
        self.posstatact.setObjectName("posstatact")
        self.genbuyfromsellact = QtGui.QAction(MainWindow)
        self.genbuyfromsellact.setObjectName("genbuyfromsellact")
        self.saveptfact = QtGui.QAction(MainWindow)
        self.saveptfact.setObjectName("saveptfact")
        self.menu.addAction(self.stockinfoact)
        self.menu.addAction(self.posstatact)
        self.menu_2.addAction(self.genbuyfromsellact)
        self.menu_2.addAction(self.saveptfact)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.optab.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabstat.setCurrentIndex(0)
        QtCore.QObject.connect(self.optab, QtCore.SIGNAL("currentChanged(int)"), self.tabstat.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EasyTrader", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "股票组合", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.buyorder.setText(QtGui.QApplication.translate("MainWindow", "买入/补买", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelbuyorder.setText(QtGui.QApplication.translate("MainWindow", "撤买", None, QtGui.QApplication.UnicodeUTF8))
        self.autosubmit_2.setText(QtGui.QApplication.translate("MainWindow", "自动下单", None, QtGui.QApplication.UnicodeUTF8))
        self.buypricefixspin.setPrefix(QtGui.QApplication.translate("MainWindow", "￥", None, QtGui.QApplication.UnicodeUTF8))
        self.buypricefixspin.setSuffix(QtGui.QApplication.translate("MainWindow", "元", None, QtGui.QApplication.UnicodeUTF8))
        self.forcecancelbuychk.setText(QtGui.QApplication.translate("MainWindow", "强撤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Txt", None, QtGui.QApplication.UnicodeUTF8))
        self.buyorder2.setText(QtGui.QApplication.translate("MainWindow", "买入(批量)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "股指期货", None, QtGui.QApplication.UnicodeUTF8))
        self.opensifbtn.setText(QtGui.QApplication.translate("MainWindow", "空开", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelopensifbtn.setText(QtGui.QApplication.translate("MainWindow", "撤单", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.openpricefixspin.setSuffix(QtGui.QApplication.translate("MainWindow", "点", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "单笔开仓", None, QtGui.QApplication.UnicodeUTF8))
        self.sopenbtn.setText(QtGui.QApplication.translate("MainWindow", "空开", None, QtGui.QApplication.UnicodeUTF8))
        self.lopenbtn.setText(QtGui.QApplication.translate("MainWindow", "多开", None, QtGui.QApplication.UnicodeUTF8))
        self.optab.setTabText(self.optab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "建仓", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "股票组合", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.sellorder.setText(QtGui.QApplication.translate("MainWindow", "卖出/补卖", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelsellorder.setText(QtGui.QApplication.translate("MainWindow", "撤卖", None, QtGui.QApplication.UnicodeUTF8))
        self.autosubmit.setText(QtGui.QApplication.translate("MainWindow", "自动下单", None, QtGui.QApplication.UnicodeUTF8))
        self.sellpricefixspin.setPrefix(QtGui.QApplication.translate("MainWindow", "￥", None, QtGui.QApplication.UnicodeUTF8))
        self.sellpricefixspin.setSuffix(QtGui.QApplication.translate("MainWindow", "元", None, QtGui.QApplication.UnicodeUTF8))
        self.forcecancelsellchk.setText(QtGui.QApplication.translate("MainWindow", "强撤", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Txt", None, QtGui.QApplication.UnicodeUTF8))
        self.sellorder2.setText(QtGui.QApplication.translate("MainWindow", "卖出(批量)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "股指期货", None, QtGui.QApplication.UnicodeUTF8))
        self.closesifbtn.setText(QtGui.QApplication.translate("MainWindow", "空平", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelclosesifbtn.setText(QtGui.QApplication.translate("MainWindow", "撤单", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.closepricefixspin.setSuffix(QtGui.QApplication.translate("MainWindow", "点", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "单笔平仓", None, QtGui.QApplication.UnicodeUTF8))
        self.sclosebtn.setText(QtGui.QApplication.translate("MainWindow", "空平", None, QtGui.QApplication.UnicodeUTF8))
        self.lclosebtn.setText(QtGui.QApplication.translate("MainWindow", "多平", None, QtGui.QApplication.UnicodeUTF8))
        self.optab.setTabText(self.optab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "平仓", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "沪深300：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "股指期货：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "基差绝对值：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "基差百分比：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "建仓信号", None, QtGui.QApplication.UnicodeUTF8))
        self.openthresholdspin.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "%   ", None, QtGui.QApplication.UnicodeUTF8))
        self.playsignalchk.setText(QtGui.QApplication.translate("MainWindow", "报警", None, QtGui.QApplication.UnicodeUTF8))
        self.closethresholdspin.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "平仓信号", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "组合操作状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "买入量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "卖出量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "持仓名称", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "组合详情", None, QtGui.QApplication.UnicodeUTF8))
        self.loadlogbtn.setText(QtGui.QApplication.translate("MainWindow", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "操作日志", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "停牌", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "可委托", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "完全买入", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "撤等成交", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "买入失败", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "撤单失败", None, QtGui.QApplication.UnicodeUTF8))
        self.tabstat.setTabText(self.tabstat.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "买入统计", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "停牌", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "可委托", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "完全卖出", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "撤等成交", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "卖出失败", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "撤单失败", None, QtGui.QApplication.UnicodeUTF8))
        self.tabstat.setTabText(self.tabstat.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "卖出统计", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "买入点数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "卖出点数", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "查看", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "操作", None, QtGui.QApplication.UnicodeUTF8))
        self.stockinfoact.setText(QtGui.QApplication.translate("MainWindow", "股份查询", None, QtGui.QApplication.UnicodeUTF8))
        self.posstatact.setText(QtGui.QApplication.translate("MainWindow", "盈亏统计", None, QtGui.QApplication.UnicodeUTF8))
        self.genbuyfromsellact.setText(QtGui.QApplication.translate("MainWindow", "生成反手买入组合", None, QtGui.QApplication.UnicodeUTF8))
        self.saveptfact.setText(QtGui.QApplication.translate("MainWindow", "保存组合", None, QtGui.QApplication.UnicodeUTF8))

import et_rc
