# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trdmasterui.ui'
#
# Created: Fri Sep 03 13:22:25 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 585)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ontopchk = QtGui.QCheckBox(self.centralwidget)
        self.ontopchk.setChecked(True)
        self.ontopchk.setObjectName("ontopchk")
        self.gridLayout_9.addWidget(self.ontopchk, 0, 0, 1, 1)
        self.confirmchk = QtGui.QCheckBox(self.centralwidget)
        self.confirmchk.setChecked(True)
        self.confirmchk.setObjectName("confirmchk")
        self.gridLayout_9.addWidget(self.confirmchk, 0, 1, 1, 1)
        self.lockchk = QtGui.QCheckBox(self.centralwidget)
        self.lockchk.setObjectName("lockchk")
        self.gridLayout_9.addWidget(self.lockchk, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(530, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 3, 1, 1)
        self.ctltab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctltab.sizePolicy().hasHeightForWidth())
        self.ctltab.setSizePolicy(sizePolicy)
        self.ctltab.setObjectName("ctltab")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.buyorder = QtGui.QPushButton(self.groupBox)
        self.buyorder.setObjectName("buyorder")
        self.gridLayout.addWidget(self.buyorder, 0, 4, 1, 1)
        self.cancelbuyorder = QtGui.QPushButton(self.groupBox)
        self.cancelbuyorder.setObjectName("cancelbuyorder")
        self.gridLayout.addWidget(self.cancelbuyorder, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pricepolicybuy = QtGui.QComboBox(self.groupBox)
        self.pricepolicybuy.setObjectName("pricepolicybuy")
        self.gridLayout.addWidget(self.pricepolicybuy, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.buypricefixspin = QtGui.QDoubleSpinBox(self.groupBox)
        self.buypricefixspin.setMinimum(-99.0)
        self.buypricefixspin.setSingleStep(0.01)
        self.buypricefixspin.setObjectName("buypricefixspin")
        self.gridLayout.addWidget(self.buypricefixspin, 0, 3, 1, 1)
        self.forcecancelbuychk = QtGui.QCheckBox(self.groupBox)
        self.forcecancelbuychk.setObjectName("forcecancelbuychk")
        self.gridLayout.addWidget(self.forcecancelbuychk, 0, 6, 1, 1)
        self.saveorder_2 = QtGui.QPushButton(self.groupBox)
        self.saveorder_2.setObjectName("saveorder_2")
        self.gridLayout.addWidget(self.saveorder_2, 0, 7, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.opensifbtn = QtGui.QPushButton(self.groupBox_2)
        self.opensifbtn.setObjectName("opensifbtn")
        self.gridLayout_3.addWidget(self.opensifbtn, 0, 4, 1, 1)
        self.cancelopensifbtn = QtGui.QPushButton(self.groupBox_2)
        self.cancelopensifbtn.setObjectName("cancelopensifbtn")
        self.gridLayout_3.addWidget(self.cancelopensifbtn, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.openpricecmbox = QtGui.QComboBox(self.groupBox_2)
        self.openpricecmbox.setObjectName("openpricecmbox")
        self.gridLayout_3.addWidget(self.openpricecmbox, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.openpricefixspin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.openpricefixspin.setSuffix("")
        self.openpricefixspin.setDecimals(1)
        self.openpricefixspin.setMinimum(-99.0)
        self.openpricefixspin.setSingleStep(0.2)
        self.openpricefixspin.setObjectName("openpricefixspin")
        self.gridLayout_3.addWidget(self.openpricefixspin, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.ctltab.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sellorder = QtGui.QPushButton(self.groupBox_3)
        self.sellorder.setObjectName("sellorder")
        self.gridLayout_4.addWidget(self.sellorder, 0, 4, 1, 1)
        self.cancelsellorder = QtGui.QPushButton(self.groupBox_3)
        self.cancelsellorder.setObjectName("cancelsellorder")
        self.gridLayout_4.addWidget(self.cancelsellorder, 0, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.pricepolicysell = QtGui.QComboBox(self.groupBox_3)
        self.pricepolicysell.setObjectName("pricepolicysell")
        self.gridLayout_4.addWidget(self.pricepolicysell, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.sellpricefixspin = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sellpricefixspin.setMinimum(-99.0)
        self.sellpricefixspin.setSingleStep(0.01)
        self.sellpricefixspin.setObjectName("sellpricefixspin")
        self.gridLayout_4.addWidget(self.sellpricefixspin, 0, 3, 1, 1)
        self.forcecancelsellchk = QtGui.QCheckBox(self.groupBox_3)
        self.forcecancelsellchk.setObjectName("forcecancelsellchk")
        self.gridLayout_4.addWidget(self.forcecancelsellchk, 0, 6, 1, 1)
        self.saveorder = QtGui.QPushButton(self.groupBox_3)
        self.saveorder.setObjectName("saveorder")
        self.gridLayout_4.addWidget(self.saveorder, 0, 7, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.closesifbtn = QtGui.QPushButton(self.groupBox_4)
        self.closesifbtn.setObjectName("closesifbtn")
        self.gridLayout_5.addWidget(self.closesifbtn, 0, 4, 1, 1)
        self.cancelclosesifbtn = QtGui.QPushButton(self.groupBox_4)
        self.cancelclosesifbtn.setObjectName("cancelclosesifbtn")
        self.gridLayout_5.addWidget(self.cancelclosesifbtn, 0, 5, 1, 1)
        self.closepricecmbox = QtGui.QComboBox(self.groupBox_4)
        self.closepricecmbox.setObjectName("closepricecmbox")
        self.gridLayout_5.addWidget(self.closepricecmbox, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.closepricefixspin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.closepricefixspin.setDecimals(1)
        self.closepricefixspin.setMinimum(-99.0)
        self.closepricefixspin.setSingleStep(0.2)
        self.closepricefixspin.setObjectName("closepricefixspin")
        self.gridLayout_5.addWidget(self.closepricefixspin, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 2, 1, 1)
        self.ctltab.addTab(self.tab_3, "")
        self.gridLayout_9.addWidget(self.ctltab, 1, 0, 1, 4)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.selall = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selall.sizePolicy().hasHeightForWidth())
        self.selall.setSizePolicy(sizePolicy)
        self.selall.setObjectName("selall")
        self.gridLayout_8.addWidget(self.selall, 0, 0, 1, 1)
        self.deselall = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deselall.sizePolicy().hasHeightForWidth())
        self.deselall.setSizePolicy(sizePolicy)
        self.deselall.setObjectName("deselall")
        self.gridLayout_8.addWidget(self.deselall, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 3, 1, 1)
        self.raisebtn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raisebtn.sizePolicy().hasHeightForWidth())
        self.raisebtn.setSizePolicy(sizePolicy)
        self.raisebtn.setObjectName("raisebtn")
        self.gridLayout_8.addWidget(self.raisebtn, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 2, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtGui.QTableView(self.tab)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_9.addWidget(self.tabWidget, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ctltab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TradeMaster", None, QtGui.QApplication.UnicodeUTF8))
        self.ontopchk.setText(QtGui.QApplication.translate("MainWindow", "在最顶端", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmchk.setText(QtGui.QApplication.translate("MainWindow", "操作需确认", None, QtGui.QApplication.UnicodeUTF8))
        self.lockchk.setText(QtGui.QApplication.translate("MainWindow", "锁定操作", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "股票买入", None, QtGui.QApplication.UnicodeUTF8))
        self.buyorder.setText(QtGui.QApplication.translate("MainWindow", "买入", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelbuyorder.setText(QtGui.QApplication.translate("MainWindow", "撤买", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "买入价格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.forcecancelbuychk.setText(QtGui.QApplication.translate("MainWindow", "强撤", None, QtGui.QApplication.UnicodeUTF8))
        self.saveorder_2.setText(QtGui.QApplication.translate("MainWindow", "保存组合", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "期货建仓", None, QtGui.QApplication.UnicodeUTF8))
        self.opensifbtn.setText(QtGui.QApplication.translate("MainWindow", "空开", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelopensifbtn.setText(QtGui.QApplication.translate("MainWindow", "撤单", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "开仓价格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.ctltab.setTabText(self.ctltab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "建仓", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "股票卖出", None, QtGui.QApplication.UnicodeUTF8))
        self.sellorder.setText(QtGui.QApplication.translate("MainWindow", "卖出", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelsellorder.setText(QtGui.QApplication.translate("MainWindow", "撤卖", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "卖出价格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.forcecancelsellchk.setText(QtGui.QApplication.translate("MainWindow", "强撤", None, QtGui.QApplication.UnicodeUTF8))
        self.saveorder.setText(QtGui.QApplication.translate("MainWindow", "保存组合", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "期货平仓", None, QtGui.QApplication.UnicodeUTF8))
        self.closesifbtn.setText(QtGui.QApplication.translate("MainWindow", "空平", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelclosesifbtn.setText(QtGui.QApplication.translate("MainWindow", "撤单", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "平仓价格", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "修正", None, QtGui.QApplication.UnicodeUTF8))
        self.ctltab.setTabText(self.ctltab.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "平仓", None, QtGui.QApplication.UnicodeUTF8))
        self.selall.setText(QtGui.QApplication.translate("MainWindow", "全选", None, QtGui.QApplication.UnicodeUTF8))
        self.deselall.setText(QtGui.QApplication.translate("MainWindow", "全不选", None, QtGui.QApplication.UnicodeUTF8))
        self.raisebtn.setText(QtGui.QApplication.translate("MainWindow", "显示窗口", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "页", None, QtGui.QApplication.UnicodeUTF8))

